[package]
name = "reddit-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
