[package]
name = "hntracker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenvy = "0.15.7"
reqwest = { version = "0.12.23", features = ["cookies"] }
scraper = "0.24.0"
tokio = { version = "1.47.1", features = ["full"] }
