services:
  karakeep-sync:
    image: ghcr.io/sidoshi/karakeep-sync:latest
    container_name: karakeep-sync
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - KS_KARAKEEP_AUTH=<your_karakeep_auth_cookie> # required
      - KS_KARAKEEP_URL=<your_karakeep_instance_url> # required
      - KS_HN_AUTH=<your_hn_auth_cookie> # required
      - KS_HN_SCHEDULE=@daily # Cron format, e.g., "@hourly", "@daily", "0 0 * * *" default is "@daily"
